global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'annotateai-cluster'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Rules files
rule_files:
  - "alert-rules.yml"
  - "recording-rules.yml"

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 10s
    metrics_path: /metrics

  # API Gateway
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8000']
    scrape_interval: 10s
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: api-gateway:8000

  # Authentication Service
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:8001']
    scrape_interval: 10s
    metrics_path: /metrics

  # AI Model Service
  - job_name: 'ai-model-service'
    static_configs:
      - targets: ['ai-model-service:8002']
    scrape_interval: 30s
    metrics_path: /metrics
    scrape_timeout: 25s

  # Pre-annotation Service
  - job_name: 'pre-annotation-service'
    static_configs:
      - targets: ['pre-annotation-service:8003']
    scrape_interval: 30s
    metrics_path: /metrics

  # Data Pipeline Service
  - job_name: 'data-pipeline-service'
    static_configs:
      - targets: ['data-pipeline:8004']
    scrape_interval: 15s
    metrics_path: /metrics

  # Training Service
  - job_name: 'training-service'
    static_configs:
      - targets: ['training-service:8005']
    scrape_interval: 30s
    metrics_path: /metrics

  # Synthetic Data Service
  - job_name: 'synthetic-data-service'
    static_configs:
      - targets: ['synthetic-data-service:8006']
    scrape_interval: 30s
    metrics_path: /metrics

  # 3D Processing Service
  - job_name: '3d-processing-service'
    static_configs:
      - targets: ['3d-processing-service:8007']
    scrape_interval: 30s
    metrics_path: /metrics

  # Video Processing Service
  - job_name: 'video-processing-service'
    static_configs:
      - targets: ['video-processing-service:8008']
    scrape_interval: 30s
    metrics_path: /metrics

  # Storage Service
  - job_name: 'storage-service'
    static_configs:
      - targets: ['storage-service:8009']
    scrape_interval: 15s
    metrics_path: /metrics

  # Asset Processor
  - job_name: 'asset-processor'
    static_configs:
      - targets: ['asset-processor:8010']
    scrape_interval: 30s
    metrics_path: /metrics

  # Collaboration Service
  - job_name: 'collaboration-service'
    static_configs:
      - targets: ['collaboration-service:8011']
    scrape_interval: 10s
    metrics_path: /metrics

  # CLIP Service
  - job_name: 'clip-service'
    static_configs:
      - targets: ['clip-service:8012']
    scrape_interval: 30s
    metrics_path: /metrics

  # Tracking Service
  - job_name: 'tracking-service'
    static_configs:
      - targets: ['tracking-service:8013']
    scrape_interval: 30s
    metrics_path: /metrics

  # Medical Imaging Service
  - job_name: 'medical-imaging-service'
    static_configs:
      - targets: ['medical-imaging-service:8014']
    scrape_interval: 30s
    metrics_path: /metrics

  # Point Cloud Service
  - job_name: 'pointcloud-service'
    static_configs:
      - targets: ['pointcloud-service:8015']
    scrape_interval: 30s
    metrics_path: /metrics

  # XR Service
  - job_name: 'xr-service'
    static_configs:
      - targets: ['xr-service:8016']
    scrape_interval: 15s
    metrics_path: /metrics

  # Database monitoring
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 15s

  # Redis monitoring
  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 15s

  # MinIO monitoring
  - job_name: 'minio-exporter'
    static_configs:
      - targets: ['minio:9000']
    scrape_interval: 15s
    metrics_path: /minio/v2/metrics/cluster

  # Node exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # cAdvisor for container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s

  # Jaeger tracing
  - job_name: 'jaeger'
    static_configs:
      - targets: ['jaeger:14269']
    scrape_interval: 15s

  # Grafana monitoring
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    scrape_interval: 30s
    metrics_path: /metrics

  # Elasticsearch monitoring
  - job_name: 'elasticsearch-exporter'
    static_configs:
      - targets: ['elasticsearch-exporter:9114']
    scrape_interval: 30s

  # Kibana monitoring
  - job_name: 'kibana'
    static_configs:
      - targets: ['kibana:5601']
    scrape_interval: 30s
    metrics_path: /api/status

  # NVIDIA GPU monitoring (if available)
  - job_name: 'nvidia-gpu-exporter'
    static_configs:
      - targets: ['nvidia-gpu-exporter:9445']
    scrape_interval: 10s

  # MLflow monitoring
  - job_name: 'mlflow'
    static_configs:
      - targets: ['mlflow:5000']
    scrape_interval: 30s

  # Airflow monitoring
  - job_name: 'airflow'
    static_configs:
      - targets: ['airflow-webserver:8080']
    scrape_interval: 30s
    metrics_path: /admin/metrics

  # Kubernetes API server (if running on k8s)
  - job_name: 'kubernetes-apiservers'
    kubernetes_sd_configs:
      - role: endpoints
    scheme: https
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    relabel_configs:
      - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
        action: keep
        regex: default;kubernetes;https

  # Kubernetes nodes
  - job_name: 'kubernetes-nodes'
    kubernetes_sd_configs:
      - role: node
    scheme: https
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)
      - target_label: __address__
        replacement: kubernetes.default.svc:443
      - source_labels: [__meta_kubernetes_node_name]
        regex: (.+)
        target_label: __metrics_path__
        replacement: /api/v1/nodes/${1}/proxy/metrics

  # Kubernetes pods
  - job_name: 'kubernetes-pods'
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: kubernetes_pod_name

# Storage configuration
storage:
  tsdb:
    path: /prometheus/data
    retention.time: 15d
    retention.size: 10GB

# Remote write configuration for long-term storage
remote_write:
  - url: "https://prometheus-remote-write.example.com/api/v1/write"
    queue_config:
      max_samples_per_send: 1000
      max_shards: 200
      capacity: 2500

# Remote read configuration
remote_read:
  - url: "https://prometheus-remote-read.example.com/api/v1/read"
    read_recent: true 